name: crud_workflow
on:
  [push]
  
jobs:
  testJob:
    runs-on: ubuntu-latest
    env:
      CRUD_DIR: "crud"
      TEST_DIR: "tests"
      
    steps:
      - name: run mongo container
        run: docker run -d --net host -e MONGO_INITDB_ROOT_USERNAME=staging_area -e MONGO_INITDB_ROOT_PASSWORD=staging_area -e MONGO_INITDB_DATABASE=staging_area mongo mongod          
          
      - name: clone this repo
        uses: actions/checkout@v2
        with:
          path: ${{ env.CRUD_DIR }}
          
      - name: build crud-service
        working-directory: ${{ env.CRUD_DIR }}
        run: docker run -v $(pwd):/crud -w /crud maven:adoptopenjdk mvn clean package
          
      - name: run crud-service inside docker container
        working-directory: ${{ env.CRUD_DIR }}
        run: docker run -d --net host -v $(pwd):/crud -w /crud maven:adoptopenjdk java -jar target/staging-area-crud-0.0.1-SNAPSHOT.jar
          
      - name: clone repo with tests
        uses: actions/checkout@v2
        with:
          repository: alexandr635/test_CRUD_serviice_with_dbs
          path: ${{ TEST_DIR }}
          
      - name: run tests
        working-directory: ${{ TEST_DIR }}
        run: docker run --net host -v $(pwd):/test -w /test maven:adoptopenjdk mvn clean
      
